name: deploy-on-merge

on:
  push:
    branches:
      - main # Any pushes into main will trigger the following jobs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@master
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Package Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: Deploy onto GH pages
        run: npm run deploy
